name: deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@master

      - name: setup keys
        env:
          DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          DEPLOY_PUBLIC_KEY: ${{ secrets.DEPLOY_PUBLIC_KEY }}
          JINO_HOST: ${{ secrets.JINO_HOST }}
          JINO_USER: kaineer
          JINO_PORT: 49250
        run: |
          SSH_PATH="$HOME/.ssh"
          mkdir -p $SSH_PATH
          touch "$SSH_PATH/known_hosts"

          echo "$DEPLOY_PRIVATE_KEY" > "$SSH_PATH/jino"
          echo "$DEPLOY_PUBLIC_KEY" > "$SSH_PATH/jino.pub"

          chmod 700 "$SSH_PATH"
          chmod 600 "$SSH_PATH/known_hosts"
          chmod 600 "$SSH_PATH/jino"
          chmod 600 "$SSH_PATH/jino.pub"

          echo "host jino"                      > "$SSH_PATH/config"
          echo "  HostName $JINO_HOST"         >> "$SSH_PATH/config"
          echo "  IdentityFile $SSH_PATH/jino" >> "$SSH_PATH/config"
          echo "  User $JINO_USER"             >> "$SSH_PATH/config"
          echo "  Port $JINO_PORT"             >> "$SSH_PATH/config"

          chmod 600 "$SSH_PATH/config"

          ssh-keyscan -t rsa -p $JINO_PORT $JINO_HOST >> "$SSH_PATH/known_hosts"

          eval $(ssh-agent)
          ssh-add "$SSH_PATH/jino"

      - name: deploy
        run: scp -R ./public/* scp://jino//home/kaineer/hosts/html

